name: CI Deploy & Health Check

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push Services to GHCR
        run: |
          for svc in $(ls services); do
            docker build -t ghcr.io/${{ github.repository }}/$svc:latest services/$svc
            docker push ghcr.io/${{ github.repository }}/$svc:latest
          done

      - name: Start for Health Check
        run: |
          docker compose up -d graph-logger event-bus neo4j
          pip install requests
          python tests/health_check.py

      - name: Cleanup
        run: docker compose down
